### ISSUE TITLE
Confusion with .^

### ISSUE THREAD

**Issue by domluna** [JuliaDiff/ReverseDiff.jl#32]
I'm confused by how `.^` works.

```julia
using ReverseDiff

x = [-1. -2; -1 -2]
y = [1.; 2]
w = [2.; 3]
b = [-3.]

ReverseDiff.@forward sigmoid(x) = 1. ./ (1. + exp(-x))
#= mse(a, y) = mean((a - y) .* (a - y)) =#
mse(a, y) = mean((a - y) .^ 2)
f1(x, y, w, b) = mse(sigmoid(x*w .+ b), y)

out = f1(x, y, w, b)
println(out)

inputs = (x, y, w, b)
result = map(similar, inputs)
f1! = ReverseDiff.compile_gradient(f1, result)

@time f1!(result, inputs)
@time f1!(result, inputs)

for r in result
    println(r)
end

#= Expected output =#
#=  =#
#= [array([[ -3.34017280e-05,  -5.01025919e-05], =#
#=        [ -6.68040138e-05,  -1.00206021e-04]]), array([[ 0.9999833], =#
#=        [ 1.9999833]]), array([[  5.01028709e-05], =#
#=        [  1.00205742e-04]]), array([ -5.01028709e-05])] =#
```

`(a - y) .^ 2` is calling https://github.com/JuliaDiff/ReverseDiff.jl/tree/master/src/derivatives#L512 which has a call to `log`, so, if some values are negative it'll throw a `DomainError`. I'm wondering what's going on here because on the surface we're just squaring values. ` mse(a, y) = mean((a - y) .* (a - y))` works as expected.

**Comment by jrevels** [comment]
This is happening because ReverseDiff is unnecessarily differentiating w.r.t. both the base and the exponent. The solution here is to modify the built-in broadcast derivative code to only compute the derivatives w.r.t. the input it really has to (this should also improve performance anyway).

In the meantime, you can circumvent this by rewriting `mse` as you suggested, or as `mean(broadcast(^, (a - y), 2))`.

Note that if your exponent was a variable derived from a differentiable input (instead of a constant), the general derivative `d(k^x)/dx` is complex when `k` is negative, and ReverseDiff isn't well-suited at the moment for complex differentiation. Special casing exponents to unroll the multiplication might circumvent this in the narrow case where `x::Integer`, but would be inefficient if `x` is too large.

**Comment by jrevels** [comment]
Thanks for reporting this! Should be fixed on master now.
