### ISSUE TITLE
Dynamic computational graph

### ISSUE THREAD

**Issue by emilemathieu** [JuliaDiff/ReverseDiff.jl#87]
Hello all,

First, thanks for your ForwardDiff and ReverseDiff packages !

Maybe that's not the right place to ask this, but would you know whether a dynamic computational graph package exists for Julia, such as [chainer](https://github.com/chainer/chainer), [dynet](https://github.com/clab/dynet) or [PyTorch](https://github.com/pytorch/pytorch) for Python ?

Have you thought of implementing something like this ? Do you know if that's possible with Julia ?

Best,
Emile

**Comment by jrevels** [comment]
ReverseDiff already supports this, though ReverseDiff is mainly optimized for the static graph use case (which is more prevalent in traditional optimization) instead of the dynamic graph use case. 

I'm currently developing a tool which uses different optimized graph structures for the static and dynamic regimes. The dynamic graph structure I'm building is pretty heavily influenced by PyTorch.

**Comment by jrevels** [comment]
Also see [Knet.jl](https://github.com/denizyuret/Knet.jl).

**Comment by emilemathieu** [comment]
Thanks @jrevels for this information !

So what is the difference between the package you are developing and Knet ?
